// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, const uint8_t *_Nonnull, int32_t, RustBuffer *_Nonnull);

// Task defined in Rust that Swift executes
typedef void (*UniFfiRustTaskCallback)(const void * _Nullable, int8_t);

// Callback to execute Rust tasks using a Swift Task
//
// Args:
//   executor: ForeignExecutor lowered into a size_t value
//   delay: Delay in MS
//   task: UniFfiRustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*UniFfiForeignExecutorCallback)(size_t, uint32_t, UniFfiRustTaskCallback _Nullable, const void * _Nullable);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Continuation callback for UniFFI Futures
typedef void (*UniFfiRustFutureContinuation)(void * _Nonnull, int8_t);

// Scaffolding functions
void uniffi_strathweb_phi_engine_fn_free_boxedphieventhandler(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_strathweb_phi_engine_fn_constructor_boxedphieventhandler_new(uint64_t handler, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_free_inferenceoptionsbuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_strathweb_phi_engine_fn_constructor_inferenceoptionsbuilder_new(RustCallStatus *_Nonnull out_status
    
);
RustBuffer uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_build(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_repeat_last_n(void*_Nonnull ptr, uint16_t repeat_last_n, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_repeat_penalty(void*_Nonnull ptr, float repeat_penalty, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_seed(void*_Nonnull ptr, uint64_t seed, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_temperature(void*_Nonnull ptr, double temperature, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_token_count(void*_Nonnull ptr, uint16_t context_window, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_top_k(void*_Nonnull ptr, uint64_t top_k, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_inferenceoptionsbuilder_with_top_p(void*_Nonnull ptr, double top_p, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_free_phiengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_strathweb_phi_engine_fn_method_phiengine_run_inference(void*_Nonnull ptr, RustBuffer prompt_text, RustBuffer conversation_context, RustBuffer inference_options, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_free_phienginebuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_strathweb_phi_engine_fn_constructor_phienginebuilder_new(RustCallStatus *_Nonnull out_status
    
);
void*_Nonnull uniffi_strathweb_phi_engine_fn_method_phienginebuilder_build(void*_Nonnull ptr, RustBuffer cache_dir, RustCallStatus *_Nonnull out_status
);
void*_Nonnull uniffi_strathweb_phi_engine_fn_method_phienginebuilder_build_stateful(void*_Nonnull ptr, RustBuffer cache_dir, RustBuffer system_instruction, RustCallStatus *_Nonnull out_status
);
int8_t uniffi_strathweb_phi_engine_fn_method_phienginebuilder_try_use_gpu(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_phienginebuilder_with_context_window(void*_Nonnull ptr, uint16_t context_window, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_phienginebuilder_with_event_handler(void*_Nonnull ptr, void*_Nonnull event_handler, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_phienginebuilder_with_flash_attention(void*_Nonnull ptr, int8_t use_flash_attention, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_phienginebuilder_with_model_provider(void*_Nonnull ptr, RustBuffer model_provider, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_phienginebuilder_with_tokenizer_provider(void*_Nonnull ptr, RustBuffer tokenizer_provider, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_free_statefulphiengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_method_statefulphiengine_clear_messsages(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_strathweb_phi_engine_fn_method_statefulphiengine_get_history(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
RustBuffer uniffi_strathweb_phi_engine_fn_method_statefulphiengine_run_inference(void*_Nonnull ptr, RustBuffer prompt_text, RustBuffer inference_options, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_init_callback_phieventhandler(ForeignCallback _Nonnull callback_stub, RustCallStatus *_Nonnull out_status
);
void uniffi_strathweb_phi_engine_fn_func_enable_tracing(RustCallStatus *_Nonnull out_status
    
);
RustBuffer ffi_strathweb_phi_engine_rustbuffer_alloc(int32_t size, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_strathweb_phi_engine_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
RustBuffer ffi_strathweb_phi_engine_rustbuffer_reserve(RustBuffer buf, int32_t additional, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_continuation_callback_set(UniFfiRustFutureContinuation _Nonnull callback
);
void ffi_strathweb_phi_engine_rust_future_poll_u8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_u8(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_u8(void* _Nonnull handle
);
uint8_t ffi_strathweb_phi_engine_rust_future_complete_u8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_i8(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_i8(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_i8(void* _Nonnull handle
);
int8_t ffi_strathweb_phi_engine_rust_future_complete_i8(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_u16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_u16(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_u16(void* _Nonnull handle
);
uint16_t ffi_strathweb_phi_engine_rust_future_complete_u16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_i16(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_i16(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_i16(void* _Nonnull handle
);
int16_t ffi_strathweb_phi_engine_rust_future_complete_i16(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_u32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_u32(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_u32(void* _Nonnull handle
);
uint32_t ffi_strathweb_phi_engine_rust_future_complete_u32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_i32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_i32(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_i32(void* _Nonnull handle
);
int32_t ffi_strathweb_phi_engine_rust_future_complete_i32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_u64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_u64(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_u64(void* _Nonnull handle
);
uint64_t ffi_strathweb_phi_engine_rust_future_complete_u64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_i64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_i64(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_i64(void* _Nonnull handle
);
int64_t ffi_strathweb_phi_engine_rust_future_complete_i64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_f32(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_f32(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_f32(void* _Nonnull handle
);
float ffi_strathweb_phi_engine_rust_future_complete_f32(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_f64(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_f64(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_f64(void* _Nonnull handle
);
double ffi_strathweb_phi_engine_rust_future_complete_f64(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_pointer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_pointer(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_pointer(void* _Nonnull handle
);
void*_Nonnull ffi_strathweb_phi_engine_rust_future_complete_pointer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_rust_buffer(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_rust_buffer(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_rust_buffer(void* _Nonnull handle
);
RustBuffer ffi_strathweb_phi_engine_rust_future_complete_rust_buffer(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
void ffi_strathweb_phi_engine_rust_future_poll_void(void* _Nonnull handle, void* _Nonnull uniffi_callback
);
void ffi_strathweb_phi_engine_rust_future_cancel_void(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_free_void(void* _Nonnull handle
);
void ffi_strathweb_phi_engine_rust_future_complete_void(void* _Nonnull handle, RustCallStatus *_Nonnull out_status
);
uint16_t uniffi_strathweb_phi_engine_checksum_func_enable_tracing(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_build(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_repeat_last_n(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_repeat_penalty(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_seed(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_temperature(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_token_count(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_top_k(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_inferenceoptionsbuilder_with_top_p(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phiengine_run_inference(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_build(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_build_stateful(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_try_use_gpu(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_with_context_window(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_with_event_handler(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_with_flash_attention(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_with_model_provider(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phienginebuilder_with_tokenizer_provider(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_statefulphiengine_clear_messsages(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_statefulphiengine_get_history(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_statefulphiengine_run_inference(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_constructor_boxedphieventhandler_new(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_constructor_inferenceoptionsbuilder_new(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_constructor_phienginebuilder_new(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phieventhandler_on_model_loaded(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phieventhandler_on_inference_token(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phieventhandler_on_inference_started(void
    
);
uint16_t uniffi_strathweb_phi_engine_checksum_method_phieventhandler_on_inference_ended(void
    
);
uint32_t ffi_strathweb_phi_engine_uniffi_contract_version(void
    
);

